[package]
name = "tracing"
version = "0.1.0"
authors = ["Prusti Devs <prusti_developers@sympa.ethz.ch>"]
edition = "2021"

[dependencies]
tracing = "0.1"
proc-macro-tracing = { path = "proc-macro-tracing" }
